spring:
  datasource:
    url: jdbc:postgresql://digital-wallet-db.cfck6648mpd0.ap-southeast-2.rds.amazonaws.com:5432/wallet
    username: wallet
    password: ${DB_PASSWORD}
    hikari:
      connection-timeout: 3000
      validation-timeout: 1000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 1500ms

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: never
      show-components: never
      probes:
        enabled: true
      group:
        liveness:
          include: ping
        readiness:
          include: db,redis,ping
